# Generated by Django 2.0.6 on 2018-06-20 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título da tarefa', max_length=50)),
                ('concluido', models.BooleanField(default=False)),
                ('descricao', models.TextField(blank=True, help_text='Descrição da tarefa.', null=True)),
                ('data_criacao', models.DateField(blank=True, null=True)),
                ('data_edicao', models.DateField(blank=True, null=True)),
                ('data_conclusao', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
